### ISSUE TITLE
Skin composer freezes when importing image

### ISSUE THREAD

**Issue by HDcokie** [raeleus/skin-composer#100]
I don't know how to explain my english isn't good but i try my best 
i was importing my image when right clicked on a file my mouse was a blue circle my pc cant handle windows 10 but i still use it. i opened browser when the process was happening and then the menu opened in my screen i tried to go to skin composer when i opened it closed my menu but skin composer didnt opened i tried to close it after some seconds i closed itself

**Comment by raeleus** [comment]
I'm having trouble reproducing this one, especially since it didn't provide an error message. I'm going to guess that Skin Composer required more resources than were available on your video card and quit. There isn't much i can do about this. Feel free to reopen if you can reproduce this in a simple example.
