### ISSUE TITLE
Insert fixed export path inside Scene Composer Settings

### ISSUE THREAD

**Issue by aallnneess** [raeleus/skin-composer#112]
The path must be searched for every time you export. 
It would be nicer to be able to specify this in the settings.

So you can export changes very fast.

Thanks

**Comment by raeleus** [comment]
The default export path is already saved per project after you export for the first time. Just make sure to save after you export for the first time. I do not want the export path to be set for new projects because of the very real (and terrifying) prospect of accidentally overwriting a skin you've exported for another project.

**Comment by aallnneess** [comment]
It's correct. It works now. Sorry for that.
