### ISSUE TITLE
Problems to run 

### ISSUE THREAD

**Issue by Neymeha** [raeleus/skin-composer#145]
java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1092)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.restartStartOnFirstThread(DesktopLauncher.java:551)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:460)

Just got that exception when tried to run. Is there any tricks to make it run properly? I got MacBook with M1, would be glad if someone could help

**Comment by raeleus** [comment]
Are you running the jar from the terminal? java - jar SkinComposer.jar
If you already are doing that, can you test Particle Park Pro? https://github.com/raeleus/Particle-Park-Pro
This one is supposed to work on m1 macs. If it does, I can compare and make sure Skin Composer starts up the same way.

**Comment by ToxicakerJL** [comment]
@raeleus I found the same issue. My mac is M2 chip. My Java version is 17. NPE always happens

**Comment by GunniBusch** [comment]
Described here https://github.com/raeleus/skin-composer/issues/138#issuecomment-1925471474

If you are under Mac, and you tried to run a jar using `java -jar`, and it does not work, try using
`java -XstartOnFirstThread -jar [jarFile]`, because MacOs needs that certain graphics things run on the AppKit thread.

For more information run `java -X`

**Comment by raeleus** [comment]
This should be resolved with the latest update.
