### ISSUE TITLE
Keep resources relative is not doing what I expect

### ISSUE THREAD

**Issue by Tibi** [raeleus/skin-composer#30]
Hi again,

When I select "Keep resources relative" in the settings page, I'd expect to have relative links in the scmp file, for example:
`fonts: [ {  file: ../fonts/small.fnt } ]`
instead, when I select this option, all resources are copied to a sub-directory `skin_data` and the links are updated to point to this new location, but they remain absolute.

It's probably just my expectations that are wrong, but can you have a look?

**Comment by raeleus** [comment]
I answered a question about this before. Although it appears to be absolute in the file, the program is going to check the relative folder for the file first. It seems unintuitive in hindsight. Why did I do this? I dunno. Maybe to make transitioning back to absolute easier. It hasn't broken anything yet and you can still move projects to different folders/computers. I'll have this closed for now until it proves otherwise.
