### ISSUE TITLE
Error Adding fonts

### ISSUE THREAD

**Issue by Vineet77** [raeleus/skin-composer#5]
I try adding fonts to my styles, but I get "Error Adding font" error. I have the write files (fnt) and the files points to the right png file. It even shows a preview of the font, but when i click ok, i get an error. 

*here is the png file, (for some reason i couldn't attach the .fnt file
![times](https://cloud.githubusercontent.com/assets/19735864/17067042/82951d88-500f-11e6-9ffa-d0273e4c3245.png)

**Comment by raeleus** [comment]
I should really implement more expressive error messages there. Expect that for the next version.

It seems to me you're making your fonts in Hiero. Hiero doesn't export fonts very efficiently for skin design. If you open the PNG in an image editing software, you'll notice that the dimensions are 512x512. This takes up a quarter of the default texture space (1024x1024). This really restricts what drawables you can place in your skin and you certainly can't have more than one font with sizes like this. If you already have a bunch of drawables and try to add this font, Skin Composer will fail and show an error because there is no space left.

One solution is to use an image editing software to crop the empty bottom portion off of the PNG. I think you'll have to manually change the dimensions specified in the FNT file. That sound like an awful pain in the ass to do, so I'd suggest not using Hiero to make your fonts. I made a video about using Shoebox to create fonts: https://www.youtube.com/watch?v=dxPf1M7YORU

Shoebox is for folks who want more control over their font design. It exports fonts without wasted space (set power of two to false) and packs the glyphs tighter, saving even more texture space. If you want something as easy as Hiero but with better functionality and options, Littera is a great online tool: http://kvazars.com/littera/ Make sure to uncheck Power of 2 and leave canvas size to auto to keep the texture small.

Anyway, that's why I imagine your font isn't working out at the moment. You can put the contents of the FNT file in pastebin.com or something and link it here if you want me to test it properly. It could be something else entirely... Thanks for sharing this issue with me.

**Comment by raeleus** [comment]
I'll consider this closed until you can give me the problematic fnt file to test.

**Comment by Vineet77** [comment]
Sorry for the late reply (I was busy with school). I used Littiera and it works perfectly. I guess you were right.do you want the problematic for file for debugging purposes?

**Comment by raeleus** [comment]
I'm glad Littera is working out for you. I don't think it would be necessary to upload. I'm squashing bugs right now and I'll likely have a proper warning dialog to prevent anything like that from happening again. Thanks!
