### ISSUE TITLE
Texture packer creates too many images

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#7]
It seems that the texture packer does not include all fonts in a single image and sometimes might [create more atlas images than necessary](https://github.com/DranikProgrammer/gdx-skins/tree/master/medieval/skin). I'm pretty sure that - at least in the example I linked - all regions (including fonts) could be on a single atlas image.

**Comment by raeleus** [comment]
Per your suggestion [here](https://github.com/czyzby/gdx-skins/pull/4), I looked into using stripWhitespace in TexturePacker. After some adjustments, I was able to include it under "Project>>Settings>>Strip whitespace on texture export".

It works well enough with BitmapFont textures and standard drawables, however it doesn't strip nine patches. I suppose that's fine since the major offenders were users of Heiro as it forces power of two BitmapFont textures.

The change is available in my latest commit. I'll have an official version out after the weekend so I can include a couple more features. Thanks for your help!
